### ISSUE TITLE
want to add target=blank for articles links

### ISSUE THREAD

**Issue by kobkob2018** [OSDC-Code-Maven/osdc-site-generator#1]
Hi @szabgab .
It would be nice if you add a taget="_BLANK" attribute in the links for articlel page and the participants pages.

this way I can search for usefull articles, but still stay in the website..

talking about these files : 
https://github.com/OSDC-Code-Maven/osdc-site-generator/blob/v1/templates/person.html
https://github.com/OSDC-Code-Maven/osdc-site-generator/blob/v1/templates/articles.html

actualy. I am goint to try and do this and make pull request...

**Comment by szabgab** [comment]
Thanks, but this is not a good idea. It is better to keep the links internal. That still allows the users to right-click on the link to open in a different tab or to press Ctrl and then click on the link to open in a new tab.
If we put target=_blank then we take away the choice of the user.

**Comment by kobkob2018** [comment]
Yes right. they can right click.. thanks for the reply
